spring.application.name=library
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=library;trustServerCertificate=true;encrypt=true
server.port=8080
spring.datasource.username=test
spring.datasource.password=123456