spring.application.name=library
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=library;trustServerCertificate=true;encrypt=true
server.port=5050
spring.datasource.username=test
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=4b6f2d8e1a3c5f7b9d0e2a4c6f8b0d2e4a6c8f0b2d4e6a8c0f2b4d6e8a0c2f4b
jwt.expiration=86400000
logging.level.org.springframework.security=TRACE